<?php

/**
 * @file
 * Os2web Hjemmeside module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function os2web_hjemmeside_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'os2web_hjemmeside/chosen';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function os2web_hjemmeside_form_editor_link_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!empty($form['advanced'])) {
    $form['advanced']['#open'] = TRUE;
  }
}
